### PR TITLE
amber-attic in its own repo

### PR DESCRIPTION
**Pull request by herby**
`amber-attic` having its own repo, things removed from amber itself, along with dependencies on jquery-ui and codemirror.

Minor complication: To develop Amber, one must clone amber-attic in `my/` directory, similarly to helios.

### CODE REVIEW

**Comment by sebastianconcept** [comment]
Fine to me @herby 
I like that the core gets cleaner and more lean with this.

**Comment by sebastianconcept** [comment]
Thanks for doing that Herbert

**Comment by hhzl** [comment]
Is very fine for me as well. I like the idea of removing jQuery from the core. Will make a lean ``the.js`` for the cases I do not need jQuery.

**Comment by sebastianconcept** [comment]
@hhzl just out of curiosity, do you have Amber apps in frontend that are not using jquery?

**Comment by herby** [comment]
@hhzl jQuery is _not_ removed from core and won't likely be, at least until #1068 is implemented and jQuery will be dependency of Web package. It was jquery-ui and codemirror what was removed.

**Comment by hhzl** [comment]
OK

**Pull request merged**
