### PR TITLE
removes heliosClass and adds classTag with a better comment

### PR DESCRIPTION
**Pull request by sebastianconcept**

### CODE REVIEW

**Comment by sebastianconcept** [comment]
@herby now we need to upgrade Helios to do the same and start using `classTag`

Also I think the version must be bumper here, yes?

And I'm not sure what to do with `config.js`, what you usually do? shouldn't we ignore it?

**Comment by herby** [comment]
Yes, regarding config.js, you should definitely clean it up. It must not be in the commit.

BTW why don't you develop Amber + Helios using the recommended way?

Regarding Helios, yes, it must be updated. In backward-compatible manner, though. Code that used heliosClass should try classTag first, then fallback to heliosClass. This Helios change should be done first, version with it released, and then this PR can be safely merged in.

**Comment by herby** [comment]
Also, since you changed API, include changes in API-CHANGES.txt as part of the PR.

Sebastian Sastre wrote:

**Comment by sebastianconcept** [comment]
Good plan about Helios.

I've updated API-CHANGES.txt

What about bower.json? it says  "version": "0.14.0-pre" shouldn't say 0.14.2? 
also.. the merge should include offer change it to 0.14.3?

**Comment by herby** [comment]
You created this branch from way past. Please rebase to master (it will solve config.js as well, because of the .gitignore), and you also will solve the conficls in the meantime (they are there, as github shows the PR cannot be automatically merged).

**Comment by herby** [comment]
Do not include version change. It is part of the release process, the release script changes version in all needed places automatically.

**Comment by sebastianconcept** [comment]
what about now?

**Comment by sebastianconcept** [comment]
reviewed and pushed with -f

**Comment by herby** [comment]
Great. Can be merged once Helios is ready.

**Pull request merged**
