### PR TITLE
added some assertions and a collection message

### PR DESCRIPTION
**Pull request by memonono94**

### CODE REVIEW

**Comment by memonono94** [comment]
Hi everyone! I added some assertions and a simple collection message, maybe it can be helpful :)

**Comment by ghost** [comment]
As CONTRIBUTING.md shows (at least it should), no contributions accepted any more in github. Use lolg.it.

**Comment by ghost** [comment]
(If I knew how to disallow PRs not to confuse, I would do it, but afaict, no way to switch off PRs for a repo)

**Comment by vendethiel** [comment]
Indeed, github doesn't have such a feature.

**Comment by memonono94** [comment]
Ups! Sorry, I didn't see the updated .md. I will try to send you those
changes using the new way.

**Pull request closed without merging**
